use_frameworks!
platform :ios, '8.0'

target "BoxBrowseSDKSampleApp" do
	pod 'box-ios-sdk', :git => "https://github.com/box/box-ios-sdk.git", :branch => "nsurlsession"
	pod 'box-ios-browse-sdk', :path => '../'
end
