#TODO Remove this internal podspecs source when the SDK is public.
source 'git@gitenterprise.inside-box.net:Mobile/box-ios-podspecs.git'
source 'https://github.com/CocoaPods/Specs.git'
pod 'box-ios-content-sdk'
pod 'MBProgressHUD', '~> 0.9.1'
